# -*- coding: utf-8 -*-
"""final14.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n99yJux8Verl71d5OJspLoc0z_upXDaq
"""

print("=" * 50)
print("โปรแกรมตรวจสอบเลขคู่ - เลขคี่")
print("=" * 50)

while True:
    try:
        number = int(input("กรอกตัวเลข (หรือพิมพ์ 0 เพื่อออก): "))

        if number == 0:
            print("ออกจากโปรแกรมเรียบร้อยแล้ว 👋")
            break

        if number % 2 == 0:
            print(f"{number} เป็นเลขคู่ ✅")
        else:
            print(f"{number} เป็นเลขคี่ 🔹")

    except ValueError:
        print("กรุณากรอก 'ตัวเลขจำนวนเต็ม' เท่านั้น ❗")

    print("-" * 50)