# -*- coding: utf-8 -*-
"""final14.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n99yJux8Verl71d5OJspLoc0z_upXDaq
"""

print("สวัสดีครับ ยินดีต้อนรับสู่ โปรเเกรมตรวจสอบเลขคู่ เลขคี่")
print("กระผมชื่อ นายชัชวินทร์ ศิริโภคา เลขที่14 ม.4/4")

number = int(input("กรอกตัวเลข: "))

if number %2 == 0:
   print("เลขคู่")
else:
   print("เลขคี่")